export const ASSET_PATHS = {
  icon_school: 'textures/icon_school.svg',
  font_chalk_jp: 'fonts/chalk_jp.otf',
  bg_home_classroom: 'textures/bg_home_classroom.webp',
  bg_classroom: 'textures/bg_classroom.webp',
  panel_character_paper: 'textures/panel_character_paper.webp',
  deco_classroom_chair: 'textures/deco_classroom_chair.webp',
  deco_classroom_desk: 'textures/deco_classroom_desk.webp',
  sym_teacher_teaching: 'textures/sym_teacher_teaching.webp',
  sym_teacher_writing: 'textures/sym_teacher_writing.webp',
  icon_caution: 'textures/icon_caution.webp',
  sym_asteria_select: 'textures/sym_asteria_select.webp',
  sym_asteria_listen: 'textures/sym_asteria_listen.webp',
  sym_asteria_slack: 'textures/sym_asteria_slack.webp',
  sym_nyx_select: 'textures/sym_nyx_select.webp',
  sym_nyx_listen: 'textures/sym_nyx_listen.webp',
  sym_nyx_slack: 'textures/sym_nyx_slack.webp',
  sym_lumi_select: 'textures/sym_lumi_select.webp',
  sym_lumi_listen: 'textures/sym_lumi_listen.webp',
  sym_lumi_slack: 'textures/sym_lumi_slack.webp',
  bg_asteria_caught: 'textures/bg_asteria_caught.webp',
  bg_asteria_timeup: 'textures/bg_asteria_timeup.webp',
  bg_asteria_win: 'textures/bg_asteria_win.webp',
  bg_nyx_caught: 'textures/bg_nyx_caught.webp',
  bg_nyx_timeup: 'textures/bg_nyx_timeup.webp',
  bg_nyx_win: 'textures/bg_nyx_win.webp',
  bg_lumi_caught: 'textures/bg_lumi_caught.webp',
  bg_lumi_timeup: 'textures/bg_lumi_timeup.webp',
  bg_lumi_win: 'textures/bg_lumi_win.webp',
  bgm_classroom_loop: 'audio/bgm_classroom_loop.mp3',
  sfx_ui_click: 'audio/sfx_ui_click.mp3',
  sfx_teacher_walk_loop: 'audio/sfx_teacher_walk_loop.mp3',
  sfx_teacher_write_loop: 'audio/sfx_teacher_write_loop.mp3',
  sfx_warning: 'audio/sfx_warning.wav',
  sfx_caught: 'audio/sfx_caught.wav',
  sfx_win: 'audio/sfx_win.wav',
} as const;

export type AssetKey = keyof typeof ASSET_PATHS;

export const ASSET_REVISIONS: Partial<Record<AssetKey, string>> = {
  sym_teacher_teaching: '2',
  sym_teacher_writing: '2',
  bg_asteria_caught: '2',
  bg_asteria_timeup: '2',
  bg_asteria_win: '2',
  bg_nyx_caught: '2',
  bg_nyx_timeup: '2',
  bg_nyx_win: '6',
};

export type AssetMap = Record<AssetKey, string>;
